import { createHash } from 'node:crypto'
import { join, relative, resolve } from 'node:path'
import { METADATA_DIR, entrypointFileName, featurePathForIr } from './layout.ts'

const METADATA_SCHEMA_VERSION = 1

export type GeneratedFile = {
  path: string
  content: string
}

export type EntrypointOptions = {
  featureName: string
  irPath: string
  runtimeImport: string
  stepsImport: string
}

export type ArtifactRequest = {
  featureName: string
  irPath: string
  outputDir: string
  acceptanceDir: string
  cwd: string
}

export type FeatureArtifacts = {
  entrypoint: GeneratedFile
  metadata: GeneratedFile
}

const posixRelative = (fromDir: string, target: string): string =>
  relative(fromDir, target).split('\\').join('/')

export function metadataFileName(featurePath: string): string {
  const slug = featurePath.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  return `${slug}.json`
}

export function relativeImportPath(fromDir: string, target: string): string {
  const importPath = posixRelative(fromDir, target)
  return importPath.startsWith('.') ? importPath : `./${importPath}`
}

export function implementationHash(files: GeneratedFile[]): string {
  const digest = createHash('sha256')
  for (const file of [...files].sort((left, right) => left.path.localeCompare(right.path))) {
    digest.update(`${file.path}\0${file.content}\0`)
  }
  return `sha256:${digest.digest('hex')}`
}

export function entrypointSource(options: EntrypointOptions): string {
  const { featureName, irPath, runtimeImport, stepsImport } = options
  const lines = [
    '// Generated by acceptance/generate-entrypoints.ts. Do not edit.',
    "import { readFileSync } from 'node:fs'",
    "import { afterAll, describe, test } from 'vitest'",
    `import type { Feature } from ${JSON.stringify(runtimeImport)}`,
    `import { expandScenarios, runExecution } from ${JSON.stringify(runtimeImport)}`,
    `import { createWorld, releaseFixtures, stepHandlers } from ${JSON.stringify(stepsImport)}`,
    '',
    `const featureIr: Feature = JSON.parse(readFileSync(${JSON.stringify(irPath)}, 'utf8'))`,
    '',
    `describe(${JSON.stringify(featureName)}, () => {`,
    '  afterAll(releaseFixtures)',
    '',
    '  for (const execution of expandScenarios(featureIr)) {',
    '    test(execution.name, async () => {',
    '      await runExecution(execution, stepHandlers, createWorld())',
    '    })',
    '  }',
    '})',
    '',
  ]
  return lines.join('\n')
}

// Both artifact paths are relative to cwd: they are recorded inside the metadata
// document, so the caller resolves them once, at the point where it writes.
export function featureArtifacts(request: ArtifactRequest): FeatureArtifacts {
  const { featureName, irPath, outputDir, acceptanceDir, cwd } = request
  const featurePath = featurePathForIr(irPath)
  const recordedIrPath = posixRelative(cwd, resolve(irPath))

  const entrypoint: GeneratedFile = {
    path: posixRelative(cwd, resolve(outputDir, entrypointFileName(irPath))),
    content: entrypointSource({
      featureName,
      irPath: recordedIrPath,
      runtimeImport: relativeImportPath(outputDir, join(acceptanceDir, 'runtime.ts')),
      stepsImport: relativeImportPath(outputDir, join(acceptanceDir, 'steps.ts')),
    }),
  }

  const document = {
    schema_version: METADATA_SCHEMA_VERSION,
    feature_path: featurePath,
    ir_path: recordedIrPath,
    implementation_hash: implementationHash([entrypoint]),
    hash_scope: 'generated_files',
    generated_files: [entrypoint.path],
  }

  return {
    entrypoint,
    metadata: {
      path: posixRelative(cwd, resolve(outputDir, METADATA_DIR, metadataFileName(featurePath))),
      content: `${JSON.stringify(document, null, 2)}\n`,
    },
  }
}
