import { describe, expect, test } from 'vitest'
import { entrypointSource, metadataFileName, relativeImportPath } from '../acceptance/generator.ts'

// A generated entry point is a source file the acceptance tier compiles and
// runs, and its bytes are what the recorded implementation hash covers. Every
// other test of the generator asks whether a particular thing is in it; this
// one asks what it is, so a line that quietly disappears is a failure rather
// than a smaller file that still happens to satisfy every `toContain`.
describe('the generated entry point', () => {
  const expected = [
    '// Generated by acceptance/generate-entrypoints.ts. Do not edit.',
    "import { readFileSync } from 'node:fs'",
    "import { afterAll, describe, test } from 'vitest'",
    'import type { Feature } from "../../../acceptance/runtime.ts"',
    'import { expandScenarios, runExecution } from "../../../acceptance/runtime.ts"',
    'import { createWorld, releaseFixtures, stepHandlers } from "../../../acceptance/steps.ts"',
    '',
    'const featureIr: Feature = JSON.parse(readFileSync("build/acceptance/ir/api-proxy.json", \'utf8\'))',
    '',
    'describe("API proxy", () => {',
    '  afterAll(releaseFixtures)',
    '',
    '  for (const execution of expandScenarios(featureIr)) {',
    '    test(execution.name, async () => {',
    '      await runExecution(execution, stepHandlers, createWorld())',
    '    })',
    '  }',
    '})',
    '',
  ].join('\n')

  test('is exactly the source the acceptance tier expects to run', () => {
    expect(entrypointSource({
      featureName: 'API proxy',
      irPath: 'build/acceptance/ir/api-proxy.json',
      runtimeImport: '../../../acceptance/runtime.ts',
      stepsImport: '../../../acceptance/steps.ts',
    })).toBe(expected)
  })
})

describe('an import path the generated file will be compiled with', () => {
  test('uses forward slashes whatever separator the platform reported', () => {
    expect(relativeImportPath('build/acceptance/generated', 'build/acceptance/generated/nested\\steps.ts'))
      .toBe('./nested/steps.ts')
  })
})

describe('the metadata file name', () => {
  test('leaves a hyphen inside the slug alone while trimming the ends', () => {
    expect(metadataFileName('-features/api-proxy.feature-')).toBe('features-api-proxy-feature.json')
  })
})
